INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (5, 'ANTIOQUIA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (8, 'ATLÁNTICO',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (11, 'BOGOTÁ, D.C.',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (13, 'BOLÍVAR',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (15, 'BOYACÁ',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (17, 'CALDAS',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (18, 'CAQUETÁ',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (19, 'CAUCA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (20, 'CESAR',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (23, 'CÓRDOBA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (25, 'CUNDINAMARCA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (27, 'CHOCÓ',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (41, 'HUILA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (44, 'LA GUAJIRA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (47, 'MAGDALENA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (50, 'META',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (52, 'NARIÑO',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (54, 'NORTE DE SANTANDER',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (63, 'QUINDIO',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (66, 'RISARALDA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (68, 'SANTANDER',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (70, 'SUCRE',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (73, 'TOLIMA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (76, 'VALLE DEL CAUCA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (81, 'ARAUCA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (85, 'CASANARE',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (86, 'PUTUMAYO',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (88, 'SAN ANDRÉS',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (91, 'AMAZONAS',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (94, 'GUAINÍA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (95, 'GUAVIARE',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (97, 'VAUPÉS',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (99, 'VICHADA',48);
INSERT INTO `tb_state`(`id`,`name`,`tb_country_id`) VALUES (9999, '',48);