INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (1, '37', 'ANDORRA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (2, '244', 'EMIRATOS ÁRABES UNIDOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (3, '13', 'AFGANISTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (4, '43', 'ANTIGUA Y BARBUDA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (5, '41', 'ANGUILA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (6, '17', 'ALBANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (7, '26', 'ARMENIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (8, '47', 'ANTILLAS HOLANDESAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (9, '40', 'ANGOLA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (10, '10', 'ANTÁRTIDA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (11, '63', 'ARGENTINA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (12, '690', 'SAMOA AMERICANA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (13, '72', 'AUSTRIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (14, '69', 'AUSTRALIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (15, '27', 'ARUBA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (16, '248', 'ISLAS GLAND');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (17, '74', 'AZERBAIYÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (18, '29', 'BOSNIA Y HERZEGOVINA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (19, '83', 'BARBADOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (20, '81', 'BANGLADESH');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (21, '87', 'BÉLGICA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (22, '31', 'BURKINA FASO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (23, '111', 'BULGARIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (24, '80', 'BAHRÉIN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (25, '115', 'BURUNDI');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (26, '229', 'BENÍN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (27, '90', 'BERMUDAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (28, '108', 'BRUNÉI');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (29, '97', 'BOLIVIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (30, '105', 'BRASIL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (31, '77', 'BAHAMAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (32, '119', 'BHUTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (33, '74', 'ISLA BOUVET');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (34, '101', 'BOTSUANA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (35, '91', 'BIELORRUSIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (36, '88', 'BELICE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (37, '149', 'CANADÁ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (38, '165', 'ISLAS COCOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (39, '888', 'REPÚBLICA DEMOCRÁTICA DEL CONGO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (40, '640', 'REPÚBLICA CENTROAFRICANA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (41, '177', 'CONGO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (42, '767', 'SUIZA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (43, '193', 'COSTA DE MARFIL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (44, '183', 'ISLAS COOK');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (45, '211', 'CHILE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (46, '145', 'CAMERÚN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (47, '215', 'CHINA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (48, '169', 'COLOMBIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (49, '196', 'COSTA RICA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (50, '199', 'CUBA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (51, '127', 'CABO VERDE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (52, '162', 'ISLA DE NAVIDAD');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (53, '221', 'CHIPRE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (54, '644', 'REPÚBLICA CHECA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (55, '23', 'ALEMANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (56, '885', 'YIBUTI');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (57, '232', 'DINAMARCA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (58, '235', 'DOMINICA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (59, '647', 'REPÚBLICA DOMINICANA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (60, '59', 'ARGELIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (61, '239', 'ECUADOR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (62, '251', 'ESTONIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (63, '240', 'EGIPTO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (64, '685', 'SAHARA OCCIDENTAL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (65, '243', 'ERITREA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (66, '245', 'ESPAÑA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (67, '253', 'ETIOPÍA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (68, '271', 'FINLANDIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (69, '870', 'FIYI');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (70, '238', 'ISLAS MALVINAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (71, '494', 'MICRONESIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (72, '259', 'ISLAS FEROE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (73, '275', 'FRANCIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (74, '281', 'GABÓN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (75, '628', 'REINO UNIDO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (76, '297', 'GRANADA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (77, '287', 'GEORGIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (78, '325', 'GUAYANA FRANCESA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (79, '289', 'GHANA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (80, '293', 'GIBRALTAR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (81, '305', 'GROENLANDIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (82, '285', 'GAMBIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (83, '329', 'GUINEA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (84, '309', 'GUADALUPE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (85, '331', 'GUINEA ECUATORIAL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (86, '301', 'GRECIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (87, '239', 'ISLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (88, '317', 'GUATEMALA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (89, '313', 'GUAM');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (90, '334', 'GUINEA-BISSAU');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (91, '337', 'GUYANA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (92, '351', 'HONG KONG');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (93, '334', 'ISLAS HEARD Y MCDONALD');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (94, '345', 'HONDURAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (95, '198', 'CROACIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (96, '341', 'HAITÍ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (97, '355', 'HUNGRÍA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (98, '365', 'INDONESIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (99, '375', 'IRLANDA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (100, '383', 'ISRAEL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (101, '361', 'INDIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (102, '787', 'TERRITORIO BRITÁNICO DEL OCÉANO ÍNDICO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (103, '369', 'IRAQ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (104, '372', 'IRÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (105, '379', 'ISLANDIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (106, '386', 'ITALIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (107, '391', 'JAMAICA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (108, '403', 'JORDANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (109, '399', 'JAPÓN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (110, '410', 'KENIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (111, '412', 'KIRGUISTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (112, '141', 'CAMBOYA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (113, '411', 'KIRIBATI');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (114, '173', 'COMORAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (115, '695', 'SAN CRISTÓBAL Y NIEVES');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (116, '187', 'COREA DEL NORTE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (117, '190', 'COREA DEL SUR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (118, '413', 'KUWAIT');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (119, '137', 'ISLAS CAIMÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (120, '406', 'KAZAJSTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (121, '420', 'LAOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (122, '431', 'LÍBANO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (123, '715', 'SANTA LUCÍA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (124, '440', 'LIECHTENSTEIN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (125, '750', 'SRI LANKA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (126, '434', 'LIBERIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (127, '426', 'LESOTHO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (128, '443', 'LITUANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (129, '445', 'LUXEMBURGO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (130, '429', 'LETONIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (131, '438', 'LIBIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (132, '474', 'MARRUECOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (133, '498', 'MÓNACO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (134, '496', 'MOLDAVIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (135, '502', 'MONTENEGRO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (136, '450', 'MADAGASCAR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (137, '472', 'ISLAS MARSHALL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (138, '448', 'MACEDONIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (139, '464', 'MALÍ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (140, '93', 'MYANMAR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (141, '497', 'MONGOLIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (142, '447', 'MACAO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (143, '469', 'ISLAS MARIANAS DEL NORTE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (144, '477', 'MARTINICA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (145, '488', 'MAURITANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (146, '501', 'MONTSERRAT');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (147, '467', 'MALTA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (148, '485', 'MAURICIO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (149, '461', 'MALDIVAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (150, '458', 'MALAUI');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (151, '493', 'MÉXICO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (152, '455', 'MALASIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (153, '508', 'MOZAMBIQUE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (154, '507', 'NAMIBIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (155, '542', 'NUEVA CALEDONIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (156, '525', 'NÍGER');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (157, '574', 'ISLA NORFOLK');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (158, '528', 'NIGERIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (159, '521', 'NICARAGUA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (160, '573', 'PAÍSES BAJOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (161, '538', 'NORUEGA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (162, '517', 'NEPAL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (163, '508', 'NAURU');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (164, '531', 'NIUE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (165, '548', 'NUEVA ZELANDA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (166, '556', 'OMÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (167, '580', 'PANAMÁ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (168, '589', 'PERÚ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (169, '599', 'POLINESIA FRANCESA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (170, '545', 'PAPÚA NUEVA GUINEA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (171, '267', 'FILIPINAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (172, '576', 'PAKISTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (173, '603', 'POLONIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (174, '700', 'SAN PEDRO Y MIQUELÓN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (175, '593', 'ISLAS PITCAIRN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (176, '611', 'PUERTO RICO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (177, '579', 'PALESTINA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (178, '607', 'PORTUGAL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (179, '578', 'PALAOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (180, '586', 'PARAGUAY');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (181, '618', 'QATAR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (182, '660', 'REUNIÓN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (183, '670', 'RUMANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (184, '32', 'SERBIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (185, '676', 'RUSIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (186, '675', 'RUANDA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (187, '53', 'ARABIA SAUDÍ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (188, '677', 'ISLAS SALOMÓN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (189, '731', 'SEYCHELLES');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (190, '759', 'SUDÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (191, '764', 'SUECIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (192, '741', 'SINGAPUR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (193, '710', 'SANTA HELENA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (194, '247', 'ESLOVENIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (195, '744', 'SVALBARD Y JAN MAYEN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (196, '246', 'ESLOVAQUIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (197, '735', 'SIERRA LEONA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (198, '697', 'SAN MARINO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (199, '728', 'SENEGAL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (200, '748', 'SOMALIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (201, '770', 'SURINAM');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (202, '720', 'SANTO TOMÉ Y PRÍNCIPE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (203, '242', 'EL SALVADOR');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (204, '744', 'SIRIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (205, '773', 'SUAZILANDIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (206, '823', 'ISLAS TURCAS Y CAICOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (207, '203', 'CHAD');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (208, '260', 'TERRITORIOS AUSTRALES FRANCESES');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (209, '800', 'TOGO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (210, '776', 'TAILANDIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (211, '774', 'TAYIKISTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (212, '805', 'TOKELAU');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (213, '788', 'TIMOR ORIENTAL');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (214, '825', 'TURKMENISTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (215, '820', 'TÚNEZ');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (216, '810', 'TONGA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (217, '827', 'TURQUÍA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (218, '815', 'TRINIDAD Y TOBAGO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (219, '828', 'TUVALU');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (220, '218', 'TAIWÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (221, '780', 'TANZANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (222, '830', 'UCRANIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (223, '833', 'UGANDA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (224, '566', 'ISLAS ULTRAMARINAS DE ESTADOS UNIDOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (225, '249', 'ESTADOS UNIDOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (226, '845', 'URUGUAY');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (227, '847', 'UZBEKISTÁN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (228, '159', 'CIUDAD DEL VATICANO');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (229, '705', 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (230, '850', 'VENEZUELA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (231, '863', 'ISLAS VÍRGENES BRITÁNICAS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (232, '866', 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (233, '855', 'VIETNAM');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (234, '551', 'VANUATU');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (235, '875', 'WALLIS Y FUTUNA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (236, '687', 'SAMOA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (237, '880', 'YEMEN');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (238, '175', 'MAYOTTE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (239, '756', 'SUDÁFRICA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (240, '890', 'ZAMBIA');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (241, '665', 'ZIMBABUE');
INSERT INTO `tb_country` (`id`, `dian_code`, `name`) VALUES (999, '999', '');

